apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-poc
  template:
    metadata:
      labels:
        app: k8s-poc
    spec:
      containers:
        - name: k8s-poc
          image: k8s-poc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-poc
spec:
  type: NodePort
  selector:
    app: k8s-poc
  ports:
    - port: 8080
      nodePort: 30007
